
###################################### Navigation english ######################################

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Products"
url = "products/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

# footer menu
[[footer]]
name = "Blog"
url = "blog/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2
